name: 自动部署
# 当有改动推送到master分支时，启动Action
on:
  push:
    branches:
      - main
      #2020年10月后github新建仓库默认分支改为main，注意更改
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 检查分支
      uses: actions/checkout@v2
      with:
        ref: main

    - name: 安装 Node
      uses: actions/setup-node@v1
      with:
        node-version: "14.x" #16.x也可以

    - name: 安装 Hexo
      run: |
        export TZ='Asia/Shanghai'
        npm install hexo-cli -g
    - name: 缓存 Hexo
      uses: actions/cache@v1
      id: cache
      with:
        path: node_modules
        key: ${{runner.OS}}-${{hashFiles('**/package-lock.json')}}

    - name: 安装依赖
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install gulp-cli -g #全局安装gulp 如果你的博客不需要他 可以不装 节省时间
        npm install
    - name: 生成静态文件
      run: |
        hexo clean 
        hexo bangumi -u #bilibili番剧更新 如果你的博客不需要他 请删除这一行
        hexo generate
        gulp # 如果你的博客不需要他 请删除这一行
  
    - name: 部署
      run: |
        git config --global user.email "i@w03.cc"
        git config --global user.name "Wlogbot"
        git clone https://github.com/wmz1024/wmz1024.github.io.git .deploy_git
        # 此处务必用HTTPS链接。SSH链接可能有权限报错的隐患
        # =====注意.deploy_git前面有个空格=====
        # 这行指令的目的是clone博客静态文件仓库，防止Hexo推送时覆盖整个静态文件仓库，而是只推送有更改的文件
        hexo deploy
    - name: 发布npm包 # 不需要请删除这一部分
      if: env.NPM_TOKEN && env.NPM_NAME
      run: |
        cd public
        node index.js
        npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        NPM_NAME: ${{ secrets.NPM_NAME }}
